import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  console.log(results);
  return (
    <div className="scrollbar-hide">
      <Head>
        <title>Hulu by Akku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}

      <Header />

      {/* nav */}
      <Nav />

      {/* results */}
      <Results results={results} />
    </div>
  );
}
export async function getServerSideProps(context) {
  console.log(context);
  const gener = context.query.gener;
  // return console.log(context);
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[gener]?.url || requests.fetchTrending.url
    }`
  ).then((response) => response.json());
  // console.log(request.results);
  return {
    props: {
      results: request.results,
    },
  };
}
